import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import type { DailyDashboard } from '../src/types/research';

const root = process.cwd();
const dataDir = path.join(root, 'data');
const reportsDir = path.join(dataDir, 'reports');

function taiwanRunTime(now = new Date()) {
  const formatter = new Intl.DateTimeFormat('en-CA', {
    timeZone: 'Asia/Taipei',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    hour12: false,
  });

  const parts = Object.fromEntries(formatter.formatToParts(now).map((part) => [part.type, part.value]));

  return {
    date: `${parts.year}-${parts.month}-${parts.day}`,
    generatedAt: `${parts.year}-${parts.month}-${parts.day}T${parts.hour}:${parts.minute}:${parts.second}+08:00`,
    displayTime: `${parts.year}-${parts.month}-${parts.day} ${parts.hour}:${parts.minute}`,
  };
}

const runTime = taiwanRunTime();

const report: DailyDashboard = {
  date: runTime.date,
  generatedAt: runTime.generatedAt,
  marketOverview:
    '本次晨報約掃描 30 則候選消息，保留 13 則。2026-06-02 台北早晨的真正新催化集中在三件事：2026-06-01 NVIDIA 與 Microsoft 發表 RTX Spark AI PC、2026-05-31 NVIDIA 宣布台積電把 AI 導入晶圓廠流程、以及 2026-05-28 Dell 把 AI server 收入展望上修至 600 億美元。近期背景則是 2026-05-06 TrendForce 上修前九大 CSP 2026 年 capex 至 8,300 億美元、2026-04-16 台積電上修全年展望與 capex、2026-03-16 Micron HBM4 量產、2026-03-04 Broadcom AI 營收加速。1 月與 3 月較早的 AI 泡沫或供應鏈結構報導僅作背景，不當成今天的新訊號。',
  marketSentiment: 'Bullish',
  topThemes: ['今日催化回到 NVIDIA / 台積電主線', 'AI 資料中心 capex 仍強但開始向電力與散熱傳導', '台灣供應鏈從晶片延伸到光通訊與電源'],
  stocksToWatch: ['NVDA', 'TSM', 'DELL', 'AVGO', 'MU', 'VRT', '2308.TW', '3017.TW', '2345.TW'],
  biggestRisk:
    '風險不是需求立刻消失，而是估值已把 2026-2027 年的大部分好消息先反映。若中東局勢推升能源與材料成本、雲端業者開始質疑 AI 投報率、或液冷/電力/光通訊瓶頸拖慢機櫃交付，第二層與第三層供應鏈股價修正可能大於龍頭。',
  watchlistAlerts: [
    'NVDA：Computex / GTC Taipei 帶來新敘事，但今天最重要的不是 AI PC，而是台積電 fab AI 與實體 AI 工具把 NVIDIA 從 GPU 延伸到製造與工廠流程。',
    'TSM：NVIDIA 導入 fab AI 是質化加分，真正量化催化仍是 2026-04-16 上修的全年展望、3nm 擴產與先進封裝吃緊。',
    'DELL：2026-05-28 財報把 AI server 2027 收入目標上調至 600 億美元，是最直接的硬體 read-through；但漲幅過大後要看毛利與交付品質。',
    'MU / HBM：HBM4 量產與 DRAM 報價上行仍正面，但記憶體向來不是能無風險長抱的線性故事。',
    'VRT / 2308.TW / 3017.TW：電力與散熱確實受惠，但這些名字更容易被題材炒過頭，最好等訂單、毛利與產能利用率佐證。',
  ],
  emotionalWarning:
    '不要把所有和 AI 有關的新聞都視為同一層級。今天真正的新資訊只有少數幾條，其餘多數是支持原有多頭論述的背景證據。先問這則消息能不能改變 12 個月營收與供應瓶頸，再決定要不要追價。',
  news: [
    {
      id: 'news-2026-06-02-fresh-nvda-msft-rtx-spark',
      title: '【今日催化】NVIDIA 與 Microsoft 發表 RTX Spark，推進本地 AI PC 與 Agent 裝置',
      source: 'NVIDIA Newsroom / Reuters, 2026-05-31 至 2026-06-01',
      date: runTime.date,
      summary:
        'NVIDIA 與 Microsoft 推出 RTX Spark 平台，主打本地端 agent、1 petaflop AI 算力與 128GB 統一記憶體。這對 PC 供應鏈是新故事，但對股票更重要的含義是 NVIDIA 正把 AI 敘事從資料中心往終端擴散，同時維持其軟硬體生態優勢。',
      relatedTickers: ['NVDA', 'MSFT', 'DELL', 'HPQ', '2454.TW'],
      impact: 'Positive',
      confidence: 'High',
    },
    {
      id: 'news-2026-06-02-fresh-nvda-tsmc-fab-ai',
      title: '【今日催化】NVIDIA 宣布台積電把 AI 導入晶圓廠設計、製程控制與缺陷檢測',
      source: 'NVIDIA Newsroom, 2026-05-31',
      date: runTime.date,
      summary:
        '這是今天最有研究價值的台灣供應鏈訊號之一。若 AI 真能提升 turnaround time、良率、能效與 fab 規劃效率，受惠不只台積電本身，也可能外溢到 EDA、檢測、設備自動化與數位分身工具供應鏈。',
      relatedTickers: ['TSM', 'NVDA', 'CDNS', 'SNPS', 'AMAT', 'ASML'],
      impact: 'Positive',
      confidence: 'High',
    },
    {
      id: 'news-2026-06-02-fresh-dell-ai-server',
      title: '【今日催化】Dell 上修全年財測，並把 FY2027 AI server 收入目標拉高到 600 億美元',
      source: 'Reuters / Dell earnings call, 2026-05-28',
      date: runTime.date,
      summary:
        'Dell 財報是目前 AI server 需求最直接的硬體證據之一。管理層同時談到記憶體價格、每日重訂價與資料中心擴建需求，對 GPU、HBM、網通、儲存與電力散熱都是正向 read-through。',
      relatedTickers: ['DELL', 'NVDA', 'MU', 'AVGO', 'SMCI', 'WDC'],
      impact: 'Positive',
      confidence: 'High',
    },
    {
      id: 'news-2026-06-02-fresh-market-ai-over-war',
      title: '【今日催化】美股 6 月 1 日由科技股領漲，市場暫時忽略中東風險',
      source: 'Reuters, 2026-06-01',
      date: runTime.date,
      summary:
        'Reuters 指出，美股主要指數靠 NVIDIA 與 Microsoft 的 AI 新題材維持在高檔附近，即使油價與地緣政治仍帶來不確定性。這說明市場現在仍願意用 AI 成長故事對沖宏觀雜音，但領漲面偏窄是警訊。',
      relatedTickers: ['NVDA', 'MSFT', 'SPY', 'QQQ', 'SOXX'],
      impact: 'Positive',
      confidence: 'High',
    },
    {
      id: 'news-2026-06-02-fresh-nvda-physical-ai-taiwan',
      title: '【今日催化】NVIDIA 發布實體 AI 開源工具，點名 Delta、Foxconn、Pegatron、TSMC 等合作夥伴',
      source: 'NVIDIA Newsroom, 2026-05-31',
      date: runTime.date,
      summary:
        '這條消息把台灣供應鏈從 AI server 再往工廠自動化、機器人與數位分身延伸。短線未必馬上轉成財務數字，但對台達電、鴻海、和碩與台積電的長期敘事是加分項。',
      relatedTickers: ['NVDA', '2308.TW', '2317.TW', '4938.TW', 'TSM'],
      impact: 'Positive',
      confidence: 'Medium',
    },
    {
      id: 'news-2026-06-02-fresh-taiwan-ai-showcase',
      title: '【今日催化】Computex 2026 在台北登場，台灣供應鏈再次成為 AI 展示主舞台',
      source: 'PR Newswire / TVBS, 2026-06-01',
      date: runTime.date,
      summary:
        'Computex 2026 的主題是 AI Together，市場焦點從晶片擴大到伺服器 ODM、液冷、電源、光通訊與機器人。這更像情緒與敘事催化，不是獨立財報催化，但短線可能強化台股 AI 供應鏈輪動。',
      relatedTickers: ['2317.TW', '2382.TW', '6669.TW', '2308.TW', '3017.TW', '2345.TW'],
      impact: 'Positive',
      confidence: 'Medium',
    },
    {
      id: 'news-2026-06-02-context-csp-capex',
      title: '【近期背景】TrendForce 上修前九大 CSP 2026 年 capex 至 8,300 億美元',
      source: 'TrendForce, 2026-05-06',
      date: runTime.date,
      summary:
        '這不是今天的新消息，但它是理解所有 AI 硬體股的重要背景。資料中心總裝置電力預估也同步上升，代表受惠鏈條從 GPU 延伸到配電、液冷與機櫃工程。',
      relatedTickers: ['NVDA', 'AVGO', 'TSM', 'MSFT', 'AMZN', 'GOOGL', 'META'],
      impact: 'Positive',
      confidence: 'High',
    },
    {
      id: 'news-2026-06-02-context-tsmc-outlook',
      title: '【近期背景】台積電 4 月上修全年營收與 capex，3nm 收入占比大幅提升',
      source: 'Reuters, 2026-04-16',
      date: runTime.date,
      summary:
        '台積電表示 AI 晶片需求持續強勁，並擴大 3nm 產能。這是台灣 AI 供應鏈最核心的基本面背景之一，也解釋為何上游製程、封裝與材料供應鏈持續受資金追捧。',
      relatedTickers: ['TSM', '2330.TW', 'ASML', 'AMAT', '8035.TW'],
      impact: 'Positive',
      confidence: 'High',
    },
    {
      id: 'news-2026-06-02-context-general-server-bottleneck',
      title: '【近期背景】TrendForce 指出 AI server 擠壓通用型 server 供應與交期',
      source: 'TrendForce, 2026-04-15',
      date: runTime.date,
      summary:
        '這條背景消息有兩個含義：第一，AI server 優先取得供應鏈資源；第二，沒有 AI 曝險的傳統伺服器零組件商反而可能受害。這有助於篩掉只是搭上題材、卻拿不到資源的公司。',
      relatedTickers: ['DELL', 'HPE', '6669.TW', '2382.TW', 'SMCI'],
      impact: 'Neutral',
      confidence: 'High',
    },
    {
      id: 'news-2026-06-02-context-ai-optics',
      title: '【近期背景】TrendForce 預估 2026 AI 光收發模組市場達 260 億美元，關鍵元件成瓶頸',
      source: 'TrendForce, 2026-04-20',
      date: runTime.date,
      summary:
        'AI 資料中心的瓶頸不只在 GPU，還在 800G/1.6T 光模組與關鍵元件。這支持智邦、Lumentum、Coherent 與更上游光元件鏈的中期研究價值。',
      relatedTickers: ['2345.TW', 'LITE', 'COHR', 'AVGO'],
      impact: 'Positive',
      confidence: 'High',
    },
    {
      id: 'news-2026-06-02-context-micron-hbm4',
      title: '【近期背景】Micron 宣布 HBM4、Gen6 SSD 與 SOCAMM2 量產，直接對準 NVIDIA Vera Rubin',
      source: 'Micron Investor Relations, 2026-03-16',
      date: runTime.date,
      summary:
        'HBM4 量產讓記憶體受惠邏輯更具體，不再只是抽象的 AI 記憶體緊缺故事。這對 Micron 與整個 HBM / 封裝 / 測試鏈都是基本面支持。',
      relatedTickers: ['MU', 'NVDA', 'TSM', 'ASX'],
      impact: 'Positive',
      confidence: 'High',
    },
    {
      id: 'news-2026-06-02-context-broadcom-ai',
      title: '【近期背景】Broadcom 1Q26 AI 營收年增 106%，並預估 2Q AI 營收達 107 億美元',
      source: 'Broadcom Investor Relations, 2026-03-04',
      date: runTime.date,
      summary:
        'Broadcom 的 custom ASIC 與 AI networking 是 NVIDIA 之外最重要的第二條主線之一。這條背景消息有助於判斷客製化加速器、交換器與光通訊鏈條是否仍在加速。',
      relatedTickers: ['AVGO', 'GOOGL', 'META', '2345.TW'],
      impact: 'Positive',
      confidence: 'High',
    },
    {
      id: 'news-2026-06-02-context-delta-power-cooling',
      title: '【近期背景】Delta 在 Computex 前釋出 800VDC 與液冷方案，凸顯台灣電力散熱鏈地位',
      source: 'TVBS, 2026-05-28',
      date: runTime.date,
      summary:
        '台達電展示 3MW CDU、液冷與高壓直流供電，呼應 AI 機櫃功率密度上升。這讓台灣第二層受惠股從單純「AI server 零件商」轉向「AI 基礎設施解決方案商」。',
      relatedTickers: ['2308.TW', '3017.TW', 'VRT', 'ETN'],
      impact: 'Positive',
      confidence: 'Medium',
    },
  ],
  themes: [
    {
      id: 'theme-2026-06-02-nvda-core',
      name: '今日催化回到 NVIDIA / 台積電主線',
      whyItMatters:
        'RTX Spark 讓終端 AI 再次升溫，但真正有定價權與高能見度的還是 NVIDIA 與台積電。新催化已從單純賣 GPU 轉向 fab AI、agent PC 與工業數位分身。',
      relatedIndustries: ['GPU', 'AI PC', '晶圓代工', 'EDA', '工廠自動化'],
      relatedCompanies: ['NVDA', 'TSM', 'MSFT', 'CDNS', 'SNPS'],
      shortTermImpact: '資金繼續往龍頭與高確定性供應鏈集中，二線名字容易跟漲但也最容易回吐。',
      longTermImpact: '若台積電 fab AI 能變成量化效率改善，AI 對半導體供應鏈的影響將從需求端延伸到製造端。',
      evidenceQuality: 'High',
    },
    {
      id: 'theme-2026-06-02-datacenter-capex',
      name: 'AI 資料中心 capex 仍強但開始向電力與散熱傳導',
      whyItMatters:
        'Dell、TrendForce 與 Delta 的訊號一致指出，AI 投資已不只是 GPU 故事，而是整個資料中心建置週期。電力、液冷、UPS、CDU 與配電系統的重要性正在上升。',
      relatedIndustries: ['AI server', '電力基礎設施', '液冷', '機櫃', '資料中心工程'],
      relatedCompanies: ['DELL', 'VRT', 'ETN', '2308.TW', '3017.TW'],
      shortTermImpact: '具備 backlog 與定價能力的基礎設施供應商可望持續受益。',
      longTermImpact: '若 AI 機櫃功率密度維持上升，電力與散熱占整體 BOM 的比重可能持續提高。',
      evidenceQuality: 'High',
    },
    {
      id: 'theme-2026-06-02-tw-hidden',
      name: '台灣供應鏈從晶片延伸到光通訊與電源',
      whyItMatters:
        '市場已認知台積電與伺服器 ODM 的價值，但光通訊、電源、散熱與測試仍是較容易被低估的層級。TrendForce 的光模組研究和 Computex 展示強化這條分支。',
      relatedIndustries: ['光通訊', '交換器', '電源', '散熱', '測試'],
      relatedCompanies: ['2345.TW', '2308.TW', '3017.TW', '2449.TW', 'LITE'],
      shortTermImpact: '具備實際出貨與客戶認證的台灣二三線供應鏈容易獲得輪動資金關注。',
      longTermImpact: '隨 800G/1.6T 與高壓供電普及，台灣供應鏈可望從零件商升級為子系統整合商。',
      evidenceQuality: 'Medium',
    },
  ],
  supplyChain: [
    {
      id: 'node-2026-06-02-nvda',
      companyName: 'NVIDIA',
      ticker: 'NVDA',
      marketCountry: '美國',
      layer: 1,
      linkedThemeId: 'theme-2026-06-02-nvda-core',
      whyItMayBenefit: 'RTX Spark、fab AI 與實體 AI 工具同時擴大 NVIDIA 從資料中心到終端、從晶片到工廠的影響力。',
      evidenceStrength: 'High',
      visibility: 'Obvious',
      keyRisk: '估值高、雲端客戶自研 ASIC、出口管制與地緣政治。',
    },
    {
      id: 'node-2026-06-02-tsm',
      companyName: '台積電',
      ticker: 'TSM',
      marketCountry: '台灣 / 美國 ADR',
      layer: 1,
      linkedThemeId: 'theme-2026-06-02-nvda-core',
      whyItMayBenefit: '既是 AI 晶片製造核心，也開始把 AI 反向導入製造流程，提高 fab 敘事層級。',
      evidenceStrength: 'High',
      visibility: 'Obvious',
      keyRisk: '高 capex、封裝瓶頸、海外廠成本與地緣政治。',
    },
    {
      id: 'node-2026-06-02-dell',
      companyName: 'Dell Technologies',
      ticker: 'DELL',
      marketCountry: '美國',
      layer: 1,
      linkedThemeId: 'theme-2026-06-02-datacenter-capex',
      whyItMayBenefit: '財報上修是 AI server 需求最直接的 read-through 之一。',
      evidenceStrength: 'High',
      visibility: 'Obvious',
      keyRisk: '低毛利 AI server mix、記憶體成本上升與大客戶集中。',
    },
    {
      id: 'node-2026-06-02-avgo',
      companyName: 'Broadcom',
      ticker: 'AVGO',
      marketCountry: '美國',
      layer: 1,
      linkedThemeId: 'theme-2026-06-02-datacenter-capex',
      whyItMayBenefit: 'AI networking 與 custom ASIC 需求持續加速，是 NVIDIA 以外最重要的雲端 AI 晶片供應商之一。',
      evidenceStrength: 'High',
      visibility: 'Obvious',
      keyRisk: '客戶集中與 AI 支出節奏轉弱。',
    },
    {
      id: 'node-2026-06-02-mu',
      companyName: 'Micron',
      ticker: 'MU',
      marketCountry: '美國',
      layer: 2,
      linkedThemeId: 'theme-2026-06-02-datacenter-capex',
      whyItMayBenefit: 'HBM4 量產與 DRAM 報價走升，讓 AI 記憶體受惠邏輯更具體。',
      evidenceStrength: 'High',
      visibility: 'Obvious',
      keyRisk: '記憶體景氣循環、ASP 波動與產能擴充帶來的反轉風險。',
    },
    {
      id: 'node-2026-06-02-vrt',
      companyName: 'Vertiv',
      ticker: 'VRT',
      marketCountry: '美國',
      layer: 2,
      linkedThemeId: 'theme-2026-06-02-datacenter-capex',
      whyItMayBenefit: 'AI 機櫃功率與液冷需求上升，直接推升 UPS、配電與熱管理需求。',
      evidenceStrength: 'Medium',
      visibility: 'Obvious',
      keyRisk: '估值過熱與市場提前反映 2027 成長。',
    },
    {
      id: 'node-2026-06-02-delta',
      companyName: '台達電',
      ticker: '2308.TW',
      marketCountry: '台灣',
      layer: 3,
      linkedThemeId: 'theme-2026-06-02-tw-hidden',
      whyItMayBenefit: '800VDC、電源櫃與液冷方案讓台達電從零件商升級為 AI 基礎設施解決方案商。',
      evidenceStrength: 'Medium',
      visibility: 'Hidden',
      keyRisk: 'AI 相關營收拆分有限，市場可能先炒題材後等財報驗證。',
    },
    {
      id: 'node-2026-06-02-auras',
      companyName: '奇鋐',
      ticker: '3017.TW',
      marketCountry: '台灣',
      layer: 3,
      linkedThemeId: 'theme-2026-06-02-tw-hidden',
      whyItMayBenefit: '液冷與高階散熱設計若加速滲透，奇鋐是台灣散熱鏈的高槓桿標的。',
      evidenceStrength: 'Medium',
      visibility: 'Hidden',
      keyRisk: '認證與量產節奏、產品組合與毛利率波動。',
    },
    {
      id: 'node-2026-06-02-accton',
      companyName: '智邦',
      ticker: '2345.TW',
      marketCountry: '台灣',
      layer: 3,
      linkedThemeId: 'theme-2026-06-02-tw-hidden',
      whyItMayBenefit: 'AI cluster 擴張需要高速交換器與 white-box 網通，智邦具備直接受惠條件。',
      evidenceStrength: 'Medium',
      visibility: 'Hidden',
      keyRisk: '客戶拉貨波動與交換器價格競爭。',
    },
    {
      id: 'node-2026-06-02-kyec',
      companyName: '京元電子',
      ticker: '2449.TW',
      marketCountry: '台灣',
      layer: 4,
      linkedThemeId: 'theme-2026-06-02-tw-hidden',
      whyItMayBenefit: 'AI 晶片測試時間與複雜度提升，若產能吃緊將增加測試環節價值。',
      evidenceStrength: 'Low',
      visibility: 'Hidden',
      keyRisk: 'AI 測試營收貢獻透明度不足。',
    },
  ],
  beneficiaries: [
    {
      id: 'benefit-2026-06-02-nvda-core',
      themeId: 'theme-2026-06-02-nvda-core',
      directBeneficiaries: ['NVDA', 'TSM', 'MSFT'],
      indirectBeneficiaries: ['CDNS', 'SNPS', 'AMAT', 'ASML'],
      hiddenBeneficiaries: ['AOI 檢測', 'fab 數位分身', '工廠自動化軟體'],
      companiesMayBeHurt: ['缺乏 AI 能力的傳統 PC 晶片供應商', '未能跟上先進製程需求的二線設備鏈'],
      reasoning: '今天的催化不只強化 AI 終端，也把台積電 fab 本身變成 AI 應用場域，讓半導體製造鏈多了一層估值敘事。',
      evidenceQuality: 'High',
      researchPriorityScore: 95,
    },
    {
      id: 'benefit-2026-06-02-datacenter-capex',
      themeId: 'theme-2026-06-02-datacenter-capex',
      directBeneficiaries: ['DELL', 'NVDA', 'AVGO', 'MU'],
      indirectBeneficiaries: ['VRT', 'ETN', '2308.TW'],
      hiddenBeneficiaries: ['電力工程', 'CDU', '高壓配電', '資料中心施工'],
      companiesMayBeHurt: ['傳統通用型 server 零組件商', '毛利差但拿不到 AI 配置資源的 OEM/ODM'],
      reasoning: 'CSP capex 與 Dell 財報一起證明 AI 基礎建設仍在擴張，但資源正集中到高附加價值環節。',
      evidenceQuality: 'High',
      researchPriorityScore: 93,
    },
    {
      id: 'benefit-2026-06-02-tw-hidden',
      themeId: 'theme-2026-06-02-tw-hidden',
      directBeneficiaries: ['2308.TW', '3017.TW', '2345.TW'],
      indirectBeneficiaries: ['2449.TW', 'LITE', 'COHR'],
      hiddenBeneficiaries: ['光元件', '測試介面', '連接器', '高壓電源模組'],
      companiesMayBeHurt: ['低速網通供應商', '低階散熱商', '只有通用 server 曝險的台廠'],
      reasoning: '台灣供應鏈的 alpha 可能來自市場還沒完全定價的二三層瓶頸，而不是已被市場充分理解的龍頭。',
      evidenceQuality: 'Medium',
      researchPriorityScore: 89,
    },
  ],
  companyResearch: [
    {
      id: 'company-2026-06-02-nvda',
      companyName: 'NVIDIA',
      ticker: 'NVDA',
      marketCountry: '美國',
      overview: 'AI GPU、AI networking、工廠 AI 與終端 AI PC 生態系龍頭。',
      businessModel: '銷售資料中心 GPU、網通、軟體平台，並把 AI 擴展到 PC、機器人與工業流程。',
      revenueDrivers: ['資料中心 GPU', 'AI networking', '雲端 capex', 'AI PC', '軟體與生態系'],
      latestFinancialReportSummary: '今日重點不是財報，而是 2026-05-31 至 2026-06-01 的產品與生態系發布把 NVIDIA 的可敘事範圍再往外擴大。',
      revenueGrowth: '短中期仍由資料中心主導，PC 與實體 AI 是新增選項價值。',
      grossMargin: '高毛利結構仍穩，但需留意客戶議價與自研晶片替代。',
      eps: '高度受 AI 基礎設施交付節奏與供應鏈瓶頸影響。',
      freeCashFlow: '現金流強，但市場已給高估值對應持續超預期。',
      valuationRisk: '只要 capex 回報率被質疑，本益比壓縮速度可能非常快。',
      technicalTrend: '多頭趨勢不變，但不適合把任何新故事都當成追價理由。',
      competitors: ['AMD', 'Broadcom ASIC 路線', '雲端自研加速器'],
      bullCase: '從訓練、推論到終端與工廠 AI 全部持續加速。',
      baseCase: '資料中心成長維持，新增業務提供敘事加分而非立刻接棒主成長。',
      bearCase: 'capex 正常化、ASIC 分流與政策限制壓低成長預期。',
      keyRisks: ['估值', '出口限制', '客戶集中', 'ASIC 替代'],
      finalView: 'Positive',
      suggestedAction: 'Watch',
      whatWouldChangeView: '若 hyperscaler capex 或 Blackwell / Rubin 交付出現明確放緩，再下修。',
    },
    {
      id: 'company-2026-06-02-tsm',
      companyName: '台積電',
      ticker: 'TSM',
      marketCountry: '台灣 / 美國 ADR',
      overview: 'AI/HPC 時代最核心的晶圓代工與先進封裝資產。',
      businessModel: '提供先進製程、成熟製程與先進封裝，主要受惠於全球高效能運算與 AI 晶片需求。',
      revenueDrivers: ['3nm / 2nm 先進製程', 'AI/HPC', 'CoWoS / 先進封裝', '主要客戶擴產'],
      latestFinancialReportSummary: '2026-04-16 上修全年展望與 capex；2026-05-31 NVIDIA 再把 fab AI 敘事加到台積電身上。',
      revenueGrowth: '基本面偏強，AI/HPC 仍是最重要驅動。',
      grossMargin: '先進製程有定價力，但海外擴廠與高 capex 會壓短期毛利。',
      eps: '高 utilisation 與先進製程 mix 有利 EPS，但成本端變化不能忽視。',
      freeCashFlow: '高 capex 期自由現金流承壓，但長期回收邏輯仍成立。',
      valuationRisk: 'AI 核心資產地位已高度被市場認知。',
      technicalTrend: '強勢但擁擠；比較適合逢回看，不適合情緒高點追。',
      competitors: ['Samsung Foundry', 'Intel Foundry'],
      bullCase: 'AI/HPC 與先進封裝需求超預期，並由 fab AI 強化效率。',
      baseCase: '需求強、估值高，必須靠逐季財報驗證。',
      bearCase: 'AI capex 放緩、封裝瓶頸或地緣風險惡化。',
      keyRisks: ['地緣政治', '高 capex', '海外廠成本', '封裝產能'],
      finalView: 'Positive',
      suggestedAction: 'Watch',
      whatWouldChangeView: '若 AI 需求與先進封裝擴產明顯失速則轉保守。',
    },
    {
      id: 'company-2026-06-02-dell',
      companyName: 'Dell Technologies',
      ticker: 'DELL',
      marketCountry: '美國',
      overview: 'AI server 需求的直接硬體 read-through 標的。',
      businessModel: '銷售伺服器、儲存與企業硬體，AI 最主要透過 GPU server 與整機交付帶動。',
      revenueDrivers: ['AI server', '企業資料中心升級', '儲存與網通搭售'],
      latestFinancialReportSummary: '2026-05-28 管理層把 FY2027 AI server 收入目標上調至 600 億美元，全年營收與獲利展望同步上修。',
      revenueGrowth: '短線很強，但成長品質要看高毛利產品占比與交付能見度。',
      grossMargin: 'AI server 收入高成長不代表毛利同步走高。',
      eps: '短期 EPS 受規模擴張支撐，但定價策略與成本控管是關鍵。',
      freeCashFlow: '大單交付可能提高營運資金壓力。',
      valuationRisk: '財報後股價漲幅過大時，最容易被毛利率與延遲交付打回來。',
      technicalTrend: '事件驅動強，但不適合無條件追價。',
      competitors: ['SMCI', 'HPE', 'Lenovo', 'ODM 直供模式'],
      bullCase: 'AI server backlog 持續擴大且毛利改善。',
      baseCase: '營收強、毛利普通，股價需要消化。',
      bearCase: '客戶延遲、記憶體成本吃掉利潤或競爭加劇。',
      keyRisks: ['毛利率', '元件成本', '大客戶集中', '題材過熱'],
      finalView: 'Neutral',
      suggestedAction: 'Wait',
      whatWouldChangeView: '若下一季證明毛利與現金流也同步改善，可轉正面。',
    },
    {
      id: 'company-2026-06-02-avgo',
      companyName: 'Broadcom',
      ticker: 'AVGO',
      marketCountry: '美國',
      overview: 'custom AI accelerator、交換器與光互連的核心受惠者。',
      businessModel: '提供 AI networking、custom ASIC、交換器、光通訊 DSP 與基礎軟體平台。',
      revenueDrivers: ['客製化 ASIC', 'AI networking', '以太網交換器', '雲端客戶 AI cluster'],
      latestFinancialReportSummary: '1Q26 AI 營收 84 億美元，年增 106%；2Q AI 營收指引 107 億美元。',
      revenueGrowth: '受惠雲端客戶自研加速器與網通架構升級。',
      grossMargin: '產品組合佳時毛利表現強，但客戶集中需持續追蹤。',
      eps: 'AI 相關高附加價值產品驅動 EPS 擴張。',
      freeCashFlow: '現金流穩健，是硬體鏈中財務體質較強的名字。',
      valuationRisk: '若市場從 GPU 外溢到 ASIC 過度樂觀，估值也會有回檔壓力。',
      technicalTrend: '結構偏多，但節奏上不適合在所有 AI 股同漲時追最擁擠的位置。',
      competitors: ['Marvell', 'NVIDIA networking', '雲端內部設計團隊'],
      bullCase: 'custom ASIC 與 Ethernet AI fabric 雙線加速。',
      baseCase: 'AI 成長強，其他業務提供現金流支撐。',
      bearCase: '客戶專案遞延或 AI networking 增速轉緩。',
      keyRisks: ['客戶集中', '專案延遲', '估值', 'AI 投資節奏'],
      finalView: 'Positive',
      suggestedAction: 'Watch',
      whatWouldChangeView: '若大客戶 capex 正常化或 ASIC 專案可見度下降則轉中性。',
    },
    {
      id: 'company-2026-06-02-mu',
      companyName: 'Micron',
      ticker: 'MU',
      marketCountry: '美國',
      overview: 'HBM / DRAM / SSD 受惠 AI 記憶體週期的核心標的。',
      businessModel: '銷售 DRAM、HBM、NAND 與資料中心 SSD。',
      revenueDrivers: ['HBM4', 'server DRAM', '資料中心 SSD', 'AI server 出貨'],
      latestFinancialReportSummary: '2026-03-16 宣布 HBM4、Gen6 SSD、SOCAMM2 量產，直接對準 NVIDIA Vera Rubin 平台。',
      revenueGrowth: '受惠 HBM 與 server memory，但仍保有典型記憶體循環特性。',
      grossMargin: '報價走升時彈性極大，反轉時也最兇。',
      eps: '高度連動 ASP 與供需循環。',
      freeCashFlow: '需觀察高 capex 與庫存管理。',
      valuationRisk: '市場容易把 AI 記憶體故事線性化，忽略循環性。',
      technicalTrend: '偏多，但要用週期股心態管理。',
      competitors: ['SK Hynix', 'Samsung'],
      bullCase: 'HBM 緊缺延續到 2027，報價與 mix 持續上行。',
      baseCase: 'AI 受惠成立，但波動仍大。',
      bearCase: '供給擴張或雲端拉貨轉弱。',
      keyRisks: ['景氣循環', '供給回升', '客戶集中', 'capex'],
      finalView: 'Positive',
      suggestedAction: 'Watch',
      whatWouldChangeView: '若 HBM / DRAM 報價與長約能見度明顯轉弱則下修。',
    },
    {
      id: 'company-2026-06-02-vrt',
      companyName: 'Vertiv',
      ticker: 'VRT',
      marketCountry: '美國',
      overview: 'AI 資料中心電力與散熱升級的代表性標的。',
      businessModel: '提供 UPS、配電、機櫃、液冷與資料中心基礎設施服務。',
      revenueDrivers: ['液冷滲透率', 'AI rack 功率密度', '資料中心擴建', 'backlog 轉營收'],
      latestFinancialReportSummary: '沒有新的公司財報催化，但多個產業訊號都在強化其受惠邏輯。',
      revenueGrowth: '隨 AI capex 擴張而受惠，但股價已提早反映不少。',
      grossMargin: '高附加價值方案能支撐毛利，但競爭與專案成本要看。',
      eps: '高成長敘事對 EPS 放大效果強，也意味失望懲罰大。',
      freeCashFlow: '專案交付節奏決定波動。',
      valuationRisk: '容易成為市場先炒題材、後要財報驗證的典型。',
      technicalTrend: '可觀察，不適合因單一新聞追價。',
      competitors: ['ETN', 'Schneider Electric', 'nVent'],
      bullCase: '液冷成為標配，power / thermal 在 AI BOM 占比持續上升。',
      baseCase: '需求強但估值高，需要回檔與財報消化。',
      bearCase: 'AI capex 正常化或資料中心建置延遲。',
      keyRisks: ['估值', '專案遞延', '競爭', 'capex 週期'],
      finalView: 'Neutral',
      suggestedAction: 'Wait',
      whatWouldChangeView: '若估值修正且訂單品質持續改善，可轉正面。',
    },
    {
      id: 'company-2026-06-02-delta',
      companyName: '台達電',
      ticker: '2308.TW',
      marketCountry: '台灣',
      overview: '台灣 AI 電源、配電與散熱鏈中最有機會從零件供應升級為方案供應的代表公司。',
      businessModel: '提供電源供應器、電源櫃、散熱、工業自動化與資料中心基礎設施方案。',
      revenueDrivers: ['AI 資料中心電源', '液冷方案', '高壓直流供電', '工業自動化'],
      latestFinancialReportSummary: 'Computex 2026 前後的產業報導聚焦其 800VDC、CDU 與液冷能力，並提到台灣新廠與升級投資。',
      revenueGrowth: '若 AI 資料中心 power / cooling 支出擴大，成長能見度有機會上修。',
      grossMargin: '相較純組裝供應商，方案導向產品有較佳議價能力。',
      eps: '仍需觀察 AI 相關營收占比擴大的速度。',
      freeCashFlow: '重資本擴產與新方案投入會影響節奏，但商業模式較一般硬體商穩定。',
      valuationRisk: '市場可能先反映 AI 題材，再等待財報證明。',
      technicalTrend: '可追蹤，但比較適合等數字與接單佐證後再加碼。',
      competitors: ['Vertiv', 'Eaton', '光寶科'],
      bullCase: '電源與液冷成為 AI 基礎建設的結構性高成長支出。',
      baseCase: 'AI 受惠成立，但需要更多財務拆分確認貢獻度。',
      bearCase: 'AI 相關收入成長不如題材想像，或競爭壓低利潤。',
      keyRisks: ['題材先行', '接單透明度', '競爭', '資本支出'],
      finalView: 'Positive',
      suggestedAction: 'Watch',
      whatWouldChangeView: '若後續財報顯示 AI 電力與散熱貢獻不如預期，需下修。',
    },
  ],
  watchlist: [
    {
      id: 'watch-2026-06-02-nvda',
      ticker: 'NVDA',
      companyName: 'NVIDIA',
      currentView: 'Positive',
      keyNews: 'RTX Spark、台積電 fab AI、實體 AI 工具三線並進。',
      keyPriceLevels: '今日不使用即時價；重點看消息是否只是情緒催化，或能轉成下季營收與供應鏈配置。',
      riskNotes: '高估值、出口限制、ASIC 分流。',
      lastUpdatedTime: runTime.displayTime,
      status: 'Watching',
    },
    {
      id: 'watch-2026-06-02-tsm',
      ticker: 'TSM',
      companyName: '台積電',
      currentView: 'Positive',
      keyNews: 'NVIDIA 公開點名台積電用 AI 強化 fab；4 月上修全年展望與 capex。',
      keyPriceLevels: '重點不是盤中價，而是後續月營收、3nm utilization 與 CoWoS 供給。',
      riskNotes: '地緣政治、高 capex、封裝瓶頸。',
      lastUpdatedTime: runTime.displayTime,
      status: 'Watching',
    },
    {
      id: 'watch-2026-06-02-dell',
      ticker: 'DELL',
      companyName: 'Dell Technologies',
      currentView: 'Neutral',
      keyNews: 'FY2027 AI server 收入目標提高至 600 億美元。',
      keyPriceLevels: '財報大漲後不追；等毛利率與現金流驗證。',
      riskNotes: 'AI server mix 高但毛利未必同步改善。',
      lastUpdatedTime: runTime.displayTime,
      status: 'Researching',
    },
    {
      id: 'watch-2026-06-02-avgo',
      ticker: 'AVGO',
      companyName: 'Broadcom',
      currentView: 'Positive',
      keyNews: '1Q26 AI 營收 84 億美元、2Q 指引 107 億美元。',
      keyPriceLevels: '重點追蹤 ASIC 專案能見度與 AI networking 需求。',
      riskNotes: '客戶集中與題材過熱。',
      lastUpdatedTime: runTime.displayTime,
      status: 'Watching',
    },
    {
      id: 'watch-2026-06-02-mu',
      ticker: 'MU',
      companyName: 'Micron',
      currentView: 'Positive',
      keyNews: 'HBM4 與 Gen6 SSD 量產，對準 NVIDIA Vera Rubin。',
      keyPriceLevels: '用景氣循環框架管理，不把 AI 題材當成去週期化證據。',
      riskNotes: '記憶體報價反轉速度快。',
      lastUpdatedTime: runTime.displayTime,
      status: 'Watching',
    },
    {
      id: 'watch-2026-06-02-vrt',
      ticker: 'VRT',
      companyName: 'Vertiv',
      currentView: 'Neutral',
      keyNews: '電力與液冷受惠邏輯持續被 Dell / TrendForce / Delta 資訊強化。',
      keyPriceLevels: '等估值與訂單品質更合理再提高動作。',
      riskNotes: '市場已提前反映很多 2027 成長。',
      lastUpdatedTime: runTime.displayTime,
      status: 'Waiting',
    },
    {
      id: 'watch-2026-06-02-delta',
      ticker: '2308.TW',
      companyName: '台達電',
      currentView: 'Positive',
      keyNews: 'Computex 展出 800VDC、液冷與 AI 資料中心解決方案。',
      keyPriceLevels: '重點看 AI 電源與散熱營收占比是否持續拉升。',
      riskNotes: '題材轉財務數字的速度未必跟股價一樣快。',
      lastUpdatedTime: runTime.displayTime,
      status: 'Watching',
    },
    {
      id: 'watch-2026-06-02-auras',
      ticker: '3017.TW',
      companyName: '奇鋐',
      currentView: 'Neutral',
      keyNews: '液冷與高階散熱仍是 AI 機櫃升級的重要方向。',
      keyPriceLevels: '等認證、量產與毛利率證據，避免單憑題材追價。',
      riskNotes: '產品週期、客戶認證與市場過熱。',
      lastUpdatedTime: runTime.displayTime,
      status: 'Researching',
    },
  ],
  ideaPipeline: [
    {
      id: 'idea-2026-06-02-nvda',
      newsId: 'news-2026-06-02-fresh-nvda-msft-rtx-spark',
      themeId: 'theme-2026-06-02-nvda-core',
      supplyChainNodeId: 'node-2026-06-02-nvda',
      companyResearchId: 'company-2026-06-02-nvda',
      finalView: 'Positive',
      explanation: '今日的新鮮催化先強化 NVIDIA 的平台敘事，再由供應鏈往下傳導，但真正高把握度的仍是龍頭本身而非泛 AI PC 題材股。',
    },
    {
      id: 'idea-2026-06-02-tsm',
      newsId: 'news-2026-06-02-fresh-nvda-tsmc-fab-ai',
      themeId: 'theme-2026-06-02-nvda-core',
      supplyChainNodeId: 'node-2026-06-02-tsm',
      companyResearchId: 'company-2026-06-02-tsm',
      finalView: 'Positive',
      explanation: '台積電從 AI 晶片代工受惠者，升級為 AI 工廠應用者，這提升了其在效率與技術領先上的敘事高度。',
    },
    {
      id: 'idea-2026-06-02-dell',
      newsId: 'news-2026-06-02-fresh-dell-ai-server',
      themeId: 'theme-2026-06-02-datacenter-capex',
      supplyChainNodeId: 'node-2026-06-02-dell',
      companyResearchId: 'company-2026-06-02-dell',
      finalView: 'Neutral',
      explanation: '需求證據很強，但股價反應已大，策略上更像等驗證後再提高權重，而不是看到新聞立刻追。',
    },
    {
      id: 'idea-2026-06-02-avgo',
      newsId: 'news-2026-06-02-context-broadcom-ai',
      themeId: 'theme-2026-06-02-datacenter-capex',
      supplyChainNodeId: 'node-2026-06-02-avgo',
      companyResearchId: 'company-2026-06-02-avgo',
      finalView: 'Positive',
      explanation: 'Broadcom 是 custom ASIC 與 AI networking 的高確定性受惠者，適合用來分散只押 NVIDIA 的集中風險。',
    },
    {
      id: 'idea-2026-06-02-mu',
      newsId: 'news-2026-06-02-context-micron-hbm4',
      themeId: 'theme-2026-06-02-datacenter-capex',
      supplyChainNodeId: 'node-2026-06-02-mu',
      companyResearchId: 'company-2026-06-02-mu',
      finalView: 'Positive',
      explanation: 'HBM4 量產讓 AI 記憶體受惠邏輯更具體，但必須用週期股框架處理，不能把受惠誤讀成無風險。',
    },
    {
      id: 'idea-2026-06-02-delta',
      newsId: 'news-2026-06-02-context-delta-power-cooling',
      themeId: 'theme-2026-06-02-tw-hidden',
      supplyChainNodeId: 'node-2026-06-02-delta',
      companyResearchId: 'company-2026-06-02-delta',
      finalView: 'Positive',
      explanation: '若市場開始把 AI 基礎建設重心從 GPU 外溢到 power / cooling，台達電這類台灣二三層供應商的 alpha 會上升。',
    },
  ],
};

async function main() {
  const json = `${JSON.stringify(report, null, 2)}\n`;
  await mkdir(reportsDir, { recursive: true });
  await writeFile(path.join(dataDir, 'latest.json'), json, 'utf8');
  await writeFile(path.join(reportsDir, `${report.date}.json`), json, 'utf8');
  console.log(`One-time research automation updated ${report.date}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
